/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Note {
  'id' : string,
  'title' : string,
  'body' : string,
  'updatedAt' : bigint,
  'projectId' : string,
}
export interface Project {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserLLMSettings { 'apiKey': string, 'model': string }
export interface ChatMessage { 'role': string, 'content': string }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'callLLM' : ActorMethod<[Array<ChatMessage>, Array<string>], string>,
  'createNote' : ActorMethod<[string, string, string], string>,
  'createProject' : ActorMethod<[string, string], string>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLLMSettings' : ActorMethod<[], [] | [UserLLMSettings]>,
  'getNotes' : ActorMethod<[string], Array<Note>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLLMSettings' : ActorMethod<[string, string], undefined>,
  'updateNote' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
