/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'updatedAt' : IDL.Int,
  'projectId' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const UserLLMSettings = IDL.Record({ 'apiKey': IDL.Text, 'model': IDL.Text });
export const ChatMessage = IDL.Record({ 'role': IDL.Text, 'content': IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'callLLM' : IDL.Func([IDL.Vec(ChatMessage), IDL.Vec(IDL.Text)], [IDL.Text], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLLMSettings' : IDL.Func([], [IDL.Opt(UserLLMSettings)], ['query']),
  'getNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLLMSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'updatedAt' : IDL.Int,
    'projectId' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const UserLLMSettings = IDL.Record({ 'apiKey': IDL.Text, 'model': IDL.Text });
  const ChatMessage = IDL.Record({ 'role': IDL.Text, 'content': IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'callLLM' : IDL.Func([IDL.Vec(ChatMessage), IDL.Vec(IDL.Text)], [IDL.Text], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLLMSettings' : IDL.Func([], [IDL.Opt(UserLLMSettings)], ['query']),
    'getNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLLMSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
